config/routes.rb
Ostapp2::Application.routes.draw do

  resources :users
get "tasks/incomplete"
  resources :tasks
get "photos/fivestar"
get "photos/search"
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	validates :caption, :description, :rating, :url, :presence => true
	validates :rating, :numericality => {:greater_than_or_equal_to =>0, :less_than_or_equal_to => 100 }
	validates :caption, :url, :uniqueness => true
end

app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :user
  validates :description, :name, :duration, :presence => true
  validates :name, :uniqueness => true
  validates_numericality_of :duration, {:greater_than_or_equal_to => 1, :less_than_or_equal_to => 240}
  validate :due_in_future, :on=>:create
  def due_in_future
    if due_date < Date.today then
      errors.add(:due_date, "cannot be in the past")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks
	has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
def search 
	terms = params[:terms].upcase 
    @photos = Photo.where(["upper(caption) like ? OR upper(description) like ?", "%#{terms}%", "%#{terms}%"]) 
    respond_to do |format| 
      format.html # search.html.erb 
      format.xml  { render :xml => @tasks } 
    end 
  end 

  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.where(['flagged == ? or flagged is null', false]) 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])
	@photo.user_id = @user.id
    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
    end
    

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end
  
  def fivestar
  	@fivestar = Photo.find_all_by_rating(100)
	respond_to do |format|
      	format.html # fivestar.html.erb
      	format.xml  { render :xml => @fivestar}
    end
  end
  
    before_filter :login
    private
  def login
    	authenticate_or_request_with_http_basic("The admin area") do |username, password|
    	@user = User.find_by_username(username)
	@user != nil && password == @user.password     
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end
  
  def incomplete
      @tasks = Task.find_all_by_complete(false)
      @overdue = Task.where(["due_date < ? and complete = ?", Date.today, false])
      respond_to do |format|
        format.html 
        format.xml  { render :xml => @tasks }
      end
  end


  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new
        respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])
	@task.user_id = @user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
  
  before_filter :login
  def login
    authenticate_or_request_with_http_basic("The task pages") do |username, password|
    	@user = User.find_by_username(username)
	@user != nil && password == @user.password   
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ostapp2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/photos.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ostapp2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= link_to 'All Photos', :controller => :photos, :action => :index %>
<%= link_to 'Five Star Photo', :controller => :photos, :action => :fivestar %>
<%= link_to 'New Photo', :controller => :photos, :action => :new %>
Signed in as: <%= @user.username %>
<%= form_tag({:action=> "search"}, :method=>"GET") do %>
  <%= label_tag(:terms, "Search for:") %>
  <%= text_field_tag(:terms) %>
  <%= submit_tag("Search") %>
<% end %>


<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
    <div class="field">
    <%= f.label :flagged %><br />
    <%= f.check_box :flagged %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_others.html.erb
<ul>
  <% photos.each do |photo| %>
    <li><%= link_to photo.caption, photo_path(photo) %></li>
	<%= render :partial=>"preview", :locals=>{ :picture=> photo} %>
  <% end %>
</ul>

app/views/photos/_preview.html.erb
<%= link_to picture do %>
  <img src="<%= picture.url %>" width="150"/>
  <br/>
  <%= truncate picture.description, :length=>40%>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/fivestar.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% if @fivestar != nil %>
<% @fivestar.each do |photo| %>
  <tr>
    <td><%= photo.caption %></td>
    <td><%= photo.description %></td>
    <td><%= photo.url %></td>
    <td><%= photo.rating %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Description</th>
    <th>Url</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.caption %></td>
    <td><%= render :partial=>"preview", :locals=>{ :picture=> photo} %></td>
    <td><%= photo.rating %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/search.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Description</th>
    <th>Url</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.caption %></td>
    <td><%= render :partial=>"preview", :locals=>{ :picture=> photo} %></td>
    <td><%= photo.rating %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>

<p>
  <b>Description:</b>
  <%= simple_format(@photo.description) %>
</p>

<p>
  <b>Url:</b>
  <%= @photo.url %>
</p>
<img src='<%= @photo.url %>'>

<p>
  <b>Rating:</b>
  <%= @photo.rating %>
</p>
<p><%= simple_format(@rating) %>
<% @stars = '&#9734;' * (@photo.rating*5/100).ceil %>
<p><%= simple_format(@stars) %></p>	    

<% if @photo.user != nil %>
  <h2>Other photos by <%= @photo.user.full_name %></h2>
  <%= render :partial=>"others", :locals=>{:photos => @photo.user.photos } %>
<% end %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/incomplete.html.erb
<h1>Incomplete tasks</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Duration</th>
    <th>Due date</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.duration %></td>
    <td><%= task.due_date %></td>
    <td><%= task.complete %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Task', new_task_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Duration</th>
    <th>Due date</th>
    <th>Time Remaining</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.duration %></td>
    <td><%= task.due_date %></td>
    <td>
    <% if task.complete == false and task.due_date >= DateTime.now %>
    <%= distance_of_time_in_words(Date.today, task.due_date) %>
    <% end %>
    </td>
    <td><%= task.complete %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Duration:</b>
  <%= @task.duration %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>Complete:</b>
  <%= @task.complete %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.full_name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @user.full_name %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>